(define (expmod base exp m)
  (cond ((= exp 0) 1)
        ((even? exp)
         (remainder (square (expmod base (/ exp 2) m))
                    m))
        (else
          (remainder (* base (expmod base (- exp 1) m))
                     m))))

(define (all-fermat-test n)
  (define (try-fermat n test-num)
    (cond ((>= test-num n)
           (display "Is prime\n"))
          (else (if (= (expmod test-num n n) test-num)
                  (try-fermat n (+ test-num 1))
                  (display "Not prime number\n")))))
  (display "Test number ")
  (display n)
  (display " ")
  (try-fermat n 2))

(newline)
(all-fermat-test 561)
(all-fermat-test 1105)
(all-fermat-test 1729)
(all-fermat-test 2465)
(all-fermat-test 2821)
(all-fermat-test 6601)
